#title: My Blog
#email: ""
#description: >-
#  My Personal Blog using Jekyll and Github Pages. Welcome!

repository: ffoxin/ffoxin.github.io
incremental: true

plugins:
- jekyll-feed
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

sass:
  sass_dir: css

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - .idea
  - .git
